#!/usr/bin/env bash

set -ex

autoflake --recursive --in-place \
  --remove-all-unused-imports \
  --ignore-init-module-imports \
  pybotx_smartapp_rpc tests
isort --profile black pybotx_smartapp_rpc tests
black pybotx_smartapp_rpc tests
