#!/usr/bin/env bash

set -ex

black --check --diff pybotx_smartapp_rpc tests
isort --profile black --check-only pybotx_smartapp_rpc tests

mypy pybotx_smartapp_rpc tests
flake8 pybotx_smartapp_rpc tests
