#!/usr/bin/env bash

set -ex

for arg in "$@"; do
  if [[ "$arg" == "-n" || "$arg" == "--numprocesses" || "$arg" == "-n"* ]]; then
    poetry run pytest "$@"
    exit 0
  fi
done

poetry run pytest -n auto "$@"
